### ISSUE TITLE
Congratulations on being accepted by CVPR2024. When will release the code ？

### ISSUE THREAD

**Issue by xiaowenhe** [VDIGPKU/DrivingGaussian#1]

**Comment by zwlvd** [comment]
The work is wonderful. I can't wait to have a try. Is there some new info about the code release?

**Comment by why529913** [comment]
I would also like to know when the code will be released？

**Comment by sgzqc** [comment]
+1

**Comment by GG-Bonds** [comment]
+1

**Comment by vobecant** [comment]
+1

**Comment by VDIGPKU** [comment]
The trained models and inference codes will be released in about 1 month or less.
