### ISSUE TITLE
KITTI360 scenes sequence?

### ISSUE THREAD

**Issue by why529913** [VDIGPKU/DrivingGaussian#12]
Hello, I would like to ask what pictures are used in each scene of kitti360?

**Comment by VDIGPKU** [comment]
We use 2 sequences for KITTI360, 2013_05_28_drive_0000_sync_image_00 from 0000000000-0000002000; 2013_05_28_drive_0002_sync_image_00 0000004391-0000010354.

**Comment by VDIGPKU** [comment]
We use 2 sequences for KITTI360, 2013_05_28_drive_0000_sync_image_00 from 0000000000 to 0000002000; 2013_05_28_drive_0002_sync_image_00 from 0000004391 to 0000014354.

**Comment by jiangxb98** [comment]
> We use 2 sequences for KITTI360, 2013_05_28_drive_0000_sync_image_00 from 0000000000 to 0000002000; 2013_05_28_drive_0002_sync_image_00 from 0000004391 to 0000014354.

The serial number is more than 10,000 frames, how many frames are actually used？
