### ISSUE TITLE
Details on LiDAR Point Cloud Initialization

### ISSUE THREAD

**Issue by fengaba1818** [VDIGPKU/DrivingGaussian#13]
Hello, 
First of all, thank you for your outstanding work. I have a few questions regarding the initialization process described in this paper:
1. 1. Are LiDAR points combined with Colmap, using visual points from Colmap to update and supplement the LiDAR points?
2. 2. Why is Dense Bundle Adjustment (DBA) necessary? The original 3DGS paper only uses sparse reconstruction from Colmap, but here DBA is mentioned.
3. 3. Are the image poses provided by the DBA in this context? When we project the LiDAR map onto each image, the camera pose for each image are required. So if the poses are already available, why is DBA needed to calculate the poses again?

For reference, the section of the paper in question is:

>  "Similar to former works [11, 33] in 3D reconstruction, we extend the dense bundle adjustment (DBA) to multicamera setup and obtain the updated LiDAR points. Experiment results prove that initializing with LiDAR prior to aligning with surrounding multi-camera aids in providing the Gaussian model with more precise geometry priors."

In my understanding, with the prior LiDAR point cloud, image poses, and camera intrinsics already available, all that seems necessary is to project the high-quality LiDAR map onto the images for coloring, thereby obtaining a colored point cloud. This colored point cloud, along with the image poses and camera intrinsics, could then be directly input into 3DGS.

**Comment by VDIGPKU** [comment]
1. Our method supports initialization using only LiDAR points or COLMAP and can also combine both for initialization; 2-3. DBA is not necessary. The image poses are obtained through coordinate transformations using the camera intrinsics and extrinsic provided by nuScenes. DBA can help calibrate them, but it is not mandatory.

**Comment by fengaba1818** [comment]
> 1. Our method supports initialization using only LiDAR points or COLMAP and can also combine both for initialization; 2-3. DBA is not necessary. The image poses are obtained through coordinate transformations using the camera intrinsics and extrinsic provided by nuScenes. DBA can help calibrate them, but it is not mandatory.

Thank you for your response, it was very helpful.
I have another question regarding the nuScenes dataset: nuScenes only provides 2D poses for the ego vehicle, could you please explain how you obtained the Z-axis poses in your paper? Specifically, what methods or transformations did you apply to accurately estimate the Z-axis position and orientation?
Thank you again for your assistance!
