### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by sonnefred** [VDIGPKU/DrivingGaussian#14]
Hi, thanks for sharing the code. I met this error when installing submodules/depth-diff-gaussian-rasterization using pip, could you tell me how to solve this? Thanks!
![图片](https://github.com/user-attachments/assets/37518c83-98c0-4703-bea4-f41757820ba6)

**Comment by VDIGPKU** [comment]
This error might be related to version mismatches (since some people have successfully installed the environment). Providing more detailed information about the version and environment configurations will help in identifying the issue. Otherwise, if you're still unable to resolve the error, please send your CUDA version and the error message to the previous application email. I will provide compatible submodules for you (please note that this might take some time:)

**Comment by sonnefred** [comment]
> This error might be related to version mismatches (since some people have successfully installed the environment). Providing more detailed information about the version and environment configurations will help in identifying the issue. Otherwise, if you're still unable to resolve the error, please send your CUDA version and the error message to the previous application email. I will provide compatible submodules for you (please note that this might take some time:)

OK, I will send it to the email address. And I also have a problem, in the following folder, do I need to change 'diff_gaussian_rasterization' to 'depth_diff_gaussian_rasterization'? If I don't do this, it will tell "package directory 'depth_diff_gaussian_rasterization' does not exist". Looking forward to your reply. Thanks.
![图片](https://github.com/user-attachments/assets/46d4a770-e0e8-4f86-bb88-d9fa53e6cae1)

**Comment by sonnefred** [comment]
> This error might be related to version mismatches (since some people have successfully installed the environment). Providing more detailed information about the version and environment configurations will help in identifying the issue. Otherwise, if you're still unable to resolve the error, please send your CUDA version and the error message to the previous application email. I will provide compatible submodules for you (please note that this might take some time:)

I have sent an email to the apllication email address. Looking forward to your reply. Thanks.

**Comment by jjlinghu** [comment]
> > This error might be related to version mismatches (since some people have successfully installed the environment). Providing more detailed information about the version and environment configurations will help in identifying the issue. Otherwise, if you're still unable to resolve the error, please send your CUDA version and the error message to the previous application email. I will provide compatible submodules for you (please note that this might take some time:)
> 
> OK, I will send it to the email address. And I also have a problem, in the following folder, do I need to change 'diff_gaussian_rasterization' to 'depth_diff_gaussian_rasterization'? If I don't do this, it will tell "package directory 'depth_diff_gaussian_rasterization' does not exist". Looking forward to your reply. Thanks. ![图片](https://private-user-images.githubusercontent.com/66628395/352359054-46d4a770-e0e8-4f86-bb88-d9fa53e6cae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjAzODQsIm5iZiI6MTcyNTUyMDA4NCwicGF0aCI6Ii82NjYyODM5NS8zNTIzNTkwNTQtNDZkNGE3NzAtZTBlOC00Zjg2LWJiODgtZDlmYTUzZTZjYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA3MDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjMyYzQwNTIzOTg4ZGE1YjAzNDRmMDEzMzFkNTllN2VkNWJmZTRiOGFjZTk4MzU3M2I5NDlmNGZmZGZkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EsUT2PQc8MThwRShV_j1loPNFM--veGY2ljrTFwCfkU)

Hi, have you solved this issue?
