### ISSUE TITLE
About code availability

### ISSUE THREAD

**Issue by CavalloneChen** [VDIGPKU/DrivingGaussian#15]
Hi, I've sent the code request through email, but have not yet received any feedback. Could you please checkout my application? (chenmaistc@gmail.com）

**Comment by achao2013** [comment]
The same question.Could you please checkout my application? (chao_jichao@hotmail.com)

**Comment by qiuqc1** [comment]
The same question.Could you please checkout my application? (yiyuchou89@bupt.edu.cn)

**Comment by VDIGPKU** [comment]
Oaky, we will check that. btw, the download links have been sent for all current requests (each request has a separate link), so if you submitted a request but did not receive a link, it's likely that the email went to our spam folder. Please try resubmitting your request with a different email address.
