### ISSUE TITLE
About KITTI360 Training and Testing

### ISSUE THREAD

**Issue by jiangxb98** [VDIGPKU/DrivingGaussian#16]
2 sequences for KITTI360, 2013_05_28_drive_0000_sync_image_00 from 0000000000 to 0000002000; 2013_05_28_drive_0002_sync_image_00 from 0000004391 to 0000014354.

The serial number is more than 10,000 frames, how many frames are actually used？How many frames of images are trained for a group?

**Comment by jiangxb98** [comment]
In Table 2, the dataset used seems different from the 5 sequences provided by DNMP.

**Comment by VDIGPKU** [comment]
These images have a similar scale to those in nuScenes, so all the images are involved in the computation.
