### ISSUE TITLE
Question about Incremental Gaussian Fusing and Optimization

### ISSUE THREAD

**Issue by altaykacan** [VDIGPKU/DrivingGaussian#2]
Thank you for your great work and sharing it! While studying your paper I was a little confused about how the 3D gaussians from different bins are created and optimized.

I am specifically confused about: "_For the subsequent bins, we use the Gaussians from the previous bin as the position priors [...]_". Could you please explain:

- How are the previous gaussians used as position priors? I thought the LiDAR pointcloud was used as initialization
- Do you also divide the whole LiDAR pointcloud into bins and use the separate pointcloud chunks to initialize new gaussians in every bin?

Another related doubt I had is regarding the optimization. As far as I can understand from Figure 3 (see below) and Figure 8, the whole map is being kept in GPU memory and optimized jointly even as new bins are added to the scene.

- Could you please confirm whether that is the case?
- Do you have any specific adjustments to the optimization strategy as the camera moves further and further from the initial bin?

![image](https://github.com/VDIGPKU/DrivingGaussian/assets/33330747/0d1e5906-b4bf-4435-81fd-679c692e3214)

Thank you in advance for your help!

**Comment by VDIGPKU** [comment]
1) The LiDAR point cloud is used as the initialization for Gaussians
2) Yeah, we divide the whole LiDAR point cloud into bins
3) During optimization,  the latter bin is stitched to the former ones directly

**Comment by Rango-T10000** [comment]
Dear author:

Thanks for your wonderful work. I have a question about the coordinate system you used in the "Incremental Static 3D Gaussians. ".

Generally, there are two kinds of coordinate system:
1. the ego car coordinate system: for example we can set the Lidar position as the origin. (Lidar is mounted on the top of the car.)
2.the global world coordinate system.

My question is that when the LiDAR pointcloud was used as initialization for the first bin, the position of the LiDAR pointcloud is regarded at the ego car coordinate or the global world coordinate system? And during the whole Incremental Static 3D Gaussians optimization, the position of the 3D GS models are at the ego car coordinate or the global world coordinate system?

@VDIGPKU Really thanks for your time.

**Comment by Rango-T10000** [comment]
And also I am little confused about whole training pipeline, the following is my understanding:

Using the bounding boxes in the dataset along with the Grounded SAM Models algorithm, the pixel values of the static background and dynamic objects in the corresponding images are extracted as the training labels. 

1.For static scenes, you use Incremental Static 3D Gaussians. The scene is uniformly divided into multiple bins along the depth direction based on the depth values of the points provided by the lidar. These bins are arranged in chronological order. Each bin may contain 1 to a maximum of several frames of images as labels. My understanding is that this training is also carried out in chronological order. First, for the first frame: the first bin is initialized using the lidar prior (including projection, DBA adjustment, etc.), then the label of the first bin is used to optimize the parameters of this initial setup. Then comes the second bin, where the Gaussian parameters of the previous bin that overlaps are directly used as the initialization for the overlapping part, and then this bin is used for rendering and optimization... until the first frame is completed. This means that the set of Gaussian spheres representing the static scene of the first frame is obtained. 

2. For dynamic objects, we use the Composite Dynamic Gaussian Graph. My understanding is that this training process is also carried out in chronological order. In the first frame, the lidar point cloud within the bounding box from the dataset is used as the Gaussian initialization. Then, the label is the pixel value extracted from the corresponding image using the Grounded SAM Models algorithm, and it is also used for the rendering optimization of the current frame. 

3. Then, combine the Gaussian sphere sets of the static scene with those of the dynamic objects into a single set. Then, perform global projection rendering to generate the image, compare it with the label to calculate the loss, and optimize the parameters of the Gaussian spheres. This global optimization is also an operation within the time sequence, within a single frame.

Is my undersatnding right? I really need your opinions. Thanks. @VDIGPKU
